services:
  app:
    build: .
    container_name: news-service
    ports:
      - "8080:8080"
    environment:
      NEW_SERVICE_API_KEY: ${NEW_SERVICE_API_KEY}
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-news
    environment:
      POSTGRES_DB: spam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
